var TEXT_SCORE       = "SCORE";
var TEXT_LEVEL_SCORE = "LEVEL SCORE";
var TEXT_TOT_SCORE = "TOTAL SCORE";
var TEXT_GAME_OVER = "GAME OVER";

var TEXT_YOU_LOST = "YOU LOST!!";
var TEXT_ERR_LS = "YOUR WEB BROWSER DOES NOT SUPPORT STORING SETTING LOCALLY. IN SAFARI, THE MOST COMMON CAUSE OF THIS IS USING 'PRIVATE BROWSING MODE'. SOME INFO MAY NOT SAVE OR SOME FEATURE MAY NOT WORK PROPERLY.";
var TEXT_CREDITS_DEVELOPED = "DEVELOPED BY";
var TEXT_PRELOADER_CONTINUE = "START";
var TEXT_ARE_SURE = "ARE YOU SURE?";
var TEXT_SELECT_LEVEL ="SELECT A LEVEL";
var TEXT_LEVEL = "LEVEL";
var TEXT_LEVEL_CLEARED = "LEVEL %s WON";
var TEXT_JUMP = "JUMP";
var TEXT_SELECT_TEAM = "SELECT YOUR TEAM";
var TEXT_LOADING = "LOADING...";
var TEXT_PLAY = "PLAY";
var TEXT_PLACE = "PLACE";
var TEXT_CONFIRM_DELETE = "ALL SAVING WILL BE DELETED! ARE YOU SURE?";
var TEXT_TUTORIAL_0 = "THIS IS THE JUMP AREA  Press OK TO CONTINUE";
var TEXT_TUTORIAL_1 = "THIS IS THE PERFECT JUMP AREA Press OK TO CONTINUE ";
var TEXT_TUTORIAL_2 = "PRESS THE OK BUTTON WHEN YOUR RUNNER'S FEET STEP ON THE JUMP AREAS Press OK TO CONTINUE";

var TEXT_BAD_JUMP = "POOR";
var TEXT_PERFECT_JUMP = "PERFECT!";
var TEXT_GOOD_JUMP = "GOOD!";

var TEXT_START_0 = "ON YOUR MARKS";
var TEXT_START_1 = "GET SET";

var TEXT_ST = "st";
var TEXT_ND = "nd";
var TEXT_RD = "rd";
var TEXT_OTHER_POS = "th";

var TEXT_SELECT_RUNNER = "SELECT RUNNER";
var TEAM_NAMES = new Array();
TEAM_NAMES[0] = "SPAIN";
TEAM_NAMES[1] = "RUSSIA";
TEAM_NAMES[2] = "FRANCE";
TEAM_NAMES[3] = "JAMAICA";
TEAM_NAMES[4] = "USA";
TEAM_NAMES[5] = "GREAT BRITAIN";
TEAM_NAMES[6] = "CUBA";
TEAM_NAMES[7] = "CHINA";

var TEXT_SHARE_IMAGE = "200x200.jpg";
var TEXT_SHARE_TITLE = "Congratulations!";
var TEXT_SHARE_MSG1 = "You collected <strong>";
var TEXT_SHARE_MSG2 = " points</strong>!<br><br>Share your score with your friends!";
var TEXT_SHARE_SHARE1 = "My score is ";
var TEXT_SHARE_SHARE2 = " points! Can you do better";